[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/.netlify/functions/share-og"
  to = "/.netlify/functions/share-og"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable prerendering for social media crawlers
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[functions]
  directory = "netlify/functions"

[[edge_functions]]
  function = "og-tags"
  path = "/*"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
